<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWuxoo4o\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWuxoo4o/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWuxoo4o.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWuxoo4o\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWuxoo4o\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wuxoo4o',
    'container.build_id' => '31227253',
    'container.build_time' => 1618776949,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWuxoo4o');
