<?php

namespace ContainerWuxoo4o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Khvj8QtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.khvj8Qt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.khvj8Qt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'adressRepository' => ['privates', 'App\\Repository\\AdressRepository', 'getAdressRepositoryService', true],
        ], [
            'adressRepository' => 'App\\Repository\\AdressRepository',
        ]);
    }
}
