<?php

namespace Container2dcYBhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ehslm62Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ehslm62' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ehslm62'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdressController::delete' => ['privates', '.service_locator.EIdMbTt', 'get_ServiceLocator_EIdMbTtService', true],
            'App\\Controller\\AdressController::edit' => ['privates', '.service_locator.EIdMbTt', 'get_ServiceLocator_EIdMbTtService', true],
            'App\\Controller\\AdressController::index' => ['privates', '.service_locator.khvj8Qt', 'get_ServiceLocator_Khvj8QtService', true],
            'App\\Controller\\AdressController::show' => ['privates', '.service_locator.EIdMbTt', 'get_ServiceLocator_EIdMbTtService', true],
            'App\\Controller\\MailController::index' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\oldController::delete' => ['privates', '.service_locator.EIdMbTt', 'get_ServiceLocator_EIdMbTtService', true],
            'App\\Controller\\oldController::edit' => ['privates', '.service_locator.EIdMbTt', 'get_ServiceLocator_EIdMbTtService', true],
            'App\\Controller\\oldController::index' => ['privates', '.service_locator.khvj8Qt', 'get_ServiceLocator_Khvj8QtService', true],
            'App\\Controller\\oldController::show' => ['privates', '.service_locator.EIdMbTt', 'get_ServiceLocator_EIdMbTtService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdressController:delete' => ['privates', '.service_locator.EIdMbTt', 'get_ServiceLocator_EIdMbTtService', true],
            'App\\Controller\\AdressController:edit' => ['privates', '.service_locator.EIdMbTt', 'get_ServiceLocator_EIdMbTtService', true],
            'App\\Controller\\AdressController:index' => ['privates', '.service_locator.khvj8Qt', 'get_ServiceLocator_Khvj8QtService', true],
            'App\\Controller\\AdressController:show' => ['privates', '.service_locator.EIdMbTt', 'get_ServiceLocator_EIdMbTtService', true],
            'App\\Controller\\MailController:index' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\oldController:delete' => ['privates', '.service_locator.EIdMbTt', 'get_ServiceLocator_EIdMbTtService', true],
            'App\\Controller\\oldController:edit' => ['privates', '.service_locator.EIdMbTt', 'get_ServiceLocator_EIdMbTtService', true],
            'App\\Controller\\oldController:index' => ['privates', '.service_locator.khvj8Qt', 'get_ServiceLocator_Khvj8QtService', true],
            'App\\Controller\\oldController:show' => ['privates', '.service_locator.EIdMbTt', 'get_ServiceLocator_EIdMbTtService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdressController::delete' => '?',
            'App\\Controller\\AdressController::edit' => '?',
            'App\\Controller\\AdressController::index' => '?',
            'App\\Controller\\AdressController::show' => '?',
            'App\\Controller\\MailController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\oldController::delete' => '?',
            'App\\Controller\\oldController::edit' => '?',
            'App\\Controller\\oldController::index' => '?',
            'App\\Controller\\oldController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdressController:delete' => '?',
            'App\\Controller\\AdressController:edit' => '?',
            'App\\Controller\\AdressController:index' => '?',
            'App\\Controller\\AdressController:show' => '?',
            'App\\Controller\\MailController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\oldController:delete' => '?',
            'App\\Controller\\oldController:edit' => '?',
            'App\\Controller\\oldController:index' => '?',
            'App\\Controller\\oldController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
